### ISSUE TITLE
Melhoria no envio de dados como JSON para o backend e tratamento de acordo com o Framework

### ISSUE THREAD

**Issue by icaromh** [neondotta/ProcureServicos#1]
https://github.com/neondotta/ProcureServicos/blob/67251be06571a4fa1d5e9af7ceb9bfbe5673800d/public/js/googleMaps.js#L125

Seria melhor mandar como `json` de verdade assim:
```js
$.ajax({
        type: "POST",
        url: "./servicesMap/closestLocations",
        data: { 
            "latitude": latitude.value, 
            "longitude": longitude.value,
            "type": "map" 
        },
        success:function(data) {
            add_markers(data);
        }   
});
```

Assim tu vai mandar para o backend uma requisição JSON correta e não precisa parsear a string, cuidar com as aspas duplas e tudo mais. Isso dentro da tua controller

Pelo que eu vi na documentação do codeigniter tu consegue testar se uma request é ajax assim
```php
if( $this->input->is_ajax_request() ):
 // é ajax
else:
 // não é ajax
endif;
``` 

Daí pode substituir:
https://github.com/neondotta/ProcureServicos/blob/67251be06571a4fa1d5e9af7ceb9bfbe5673800d/application/controllers/ServicesMap.php#L33-L34

Por:
```php
if( $this->input->is_ajax_request() ) {
    $location = json_decode($this->input->post()); // não sei exatamente como pegar aqui :) 
    // tem que debugar daí
```

[Referência is_ajax_request](http://codeigniter.com/user_guide/libraries/input.html#CI_Input::is_ajax_request)
[Referência input->post()](http://codeigniter.com/user_guide/libraries/input.html#CI_Input::post)

**Comment by neondotta** [comment]
https://github.com/neondotta/ProcureServicos/commit/ab8b8ed20c28f3cfedfb21fd579af506f2ca133d

**Comment by icaromh** [comment]
@neondotta Curti muito :D
