### ISSUE TITLE
Não consigo clicar nos campos do formulário

### ISSUE THREAD

**Issue by icaromh** [neondotta/ProcureServicos#10]
O foco não vai pro campo, só se uso o TAB

![screen shot 2017-09-28 at 16 57 26](https://user-images.githubusercontent.com/3057676/30987664-34c3a584-a46e-11e7-998e-1578d2f8481f.png)

**Comment by neondotta** [comment]
Problema já localizado e ajustado.
Será implementado no próximo deploy
