### ISSUE TITLE
Erro ao logar

### ISSUE THREAD

**Issue by icaromh** [neondotta/ProcureServicos#5]
https://github.com/neondotta/ProcureServicos/blob/f8192dc3476fed8b112cfed29c1632e7b71d600d/application/models/user/UserModel.php#L19-L22

Tá retornando erro ao não encontrar nada no banco (aparentemente)
```
An uncaught Exception was encountered

Type: Error

Message: Call to a member function row_array() on boolean

Filename: /app/application/models/user/UserModel.php

Line Number: 21

Backtrace:

File: /app/application/controllers/LoginController.php
Line: 27
Function: authLogin

File: /app/index.php
Line: 315
Function: require_once
```

**Comment by neondotta** [comment]
0bef20a7465323fcc89f1ff32f346d72e9f796e2

**Comment by icaromh** [comment]
o https://github.com/neondotta/ProcureServicos/pull/6 corrigiu o erro né? Acho que pode fechar essa issue aqui
