### ISSUE TITLE
Erro ao renderizar form cadastro

### ISSUE THREAD

**Issue by icaromh** [neondotta/ProcureServicos#8]
![screen shot 2017-09-27 at 10 44 58](https://user-images.githubusercontent.com/3057676/30916901-f00f51e8-a370-11e7-84c8-7f2fa2094e95.png)

Tu tá programando no windows onde `FORM.PHP == form.php` quando tu importa algum file.
Sistemas unix tem diferença entre `Form` e `form` em nome de arquivos. 

Toma cuidado com o nome dos arquivos e a forma de carregá-los

**Comment by neondotta** [comment]
Feito, será subido no próximo commit.

**Comment by neondotta** [comment]
Problema corrigido e funcionado.
