### ISSUE TITLE
Erro ao navegar no menu

### ISSUE THREAD

**Issue by icaromh** [neondotta/ProcureServicos#9]
Quando tu navega pra uma página em segundo nível e clica no menu para ir para o login, por exemplo. Acontece esse erro:

![screen shot 2017-09-27 at 10 45 42](https://user-images.githubusercontent.com/3057676/30917011-44d90890-a371-11e7-8509-6c7375e15177.png)

Bem provável que seja porque o href dos links não é absoluto e sim relativo a página que tu te encontra:
![screen shot 2017-09-27 at 10 47 13](https://user-images.githubusercontent.com/3057676/30917010-44adbb90-a371-11e7-871c-2abe8005414e.png)

ACHO que tá faltando coisa aqui nessas linhas:
https://github.com/neondotta/ProcureServicos/blob/7531466542f04314f70528867f14ca5dc65771b2/application/views/theme/header.php#L24-L33

a `24` tá diferente da `31`e `32`

**Comment by neondotta** [comment]
problema ajustado e funcionando ! \o
